name: dnd_interactive
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  shelf: ^0.7.5
  shelf_web_socket: ^0.2.3
  web_socket_channel: ^1.1.0
  crypt: ^4.0.1
  random_string: ^2.1.0
  path: ^1.7.0
  meta: ^1.3.0
  mailer: ^3.0.0
  web_whiteboard:
    git: https://github.com/doodlezucc/web_whiteboard.git
  web_polymask:
    git: https://github.com/doodlezucc/web_polymask.git
  async: ^2.7.0
  archive: ^3.1.2

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0