name: dnd_interactive
description: An online platform to gather and play tabletop RPGs.
# version: 1.0.0
homepage: https://theoretically.online/dnd

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  archive: ^3.1.6
  args: ^2.3.0
  async: ^2.8.2
  crypt: ^4.0.1
  googleapis_auth: ^1.3.0
  image: ^3.0.8
  intl: ^0.17.0
  mailer: ^5.0.2
  meta: ^1.3.0
  path: ^1.7.0
  prompts: ^2.0.0
  random_string: ^2.1.0
  shelf: ^1.2.0
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.1.0
  ambience:
    git: https://github.com/doodlezucc/ambience.git
  web_polymask:
    git: https://github.com/doodlezucc/web_polymask.git
  web_whiteboard:
    git: https://github.com/doodlezucc/web_whiteboard.git

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1