name: dnd_interactive
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  archive: ^3.1.6
  args: ^2.3.0
  async: ^2.8.2
  crypt: ^4.0.1
  mailer: ^5.0.2
  meta: ^1.3.0
  path: ^1.7.0
  random_string: ^2.1.0
  shelf: ^1.2.0
  shelf_web_socket: ^1.0.1
  web_socket_channel: ^2.1.0
  web_whiteboard:
    git: https://github.com/doodlezucc/web_whiteboard.git
  web_polymask:
    git: https://github.com/doodlezucc/web_polymask.git
  ambience:
    git: https://github.com/doodlezucc/ambience.git
  image: ^3.0.8

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1